#spring.application.name=basic

#?? ??? .properties ???? ?? ??
#.??? ????? ?? => ??? : ??? ??? ???? ??.
#server.port=8081

#?? ??? .yml ?? .yaml ???? ?? ??
#???? ??? ??? ????? ??
#server:
#   port: 8081

spring:
#  ??? jdbc?? db????? jdbc????? mybatis, jpa? ?? ??? ??? ?
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/basic
    username: root
    password: 1234
  jpa:
    database: mysql
#    innoDB사용 설정
    database-platform: org.hibernate.dialect.MariaDBDialect
#    ddl은 자동생성, 테이블은 자동반영(생성)해주나, 스키마는 반드시 사전에 생성필요.
    generate-ddl: true
    hibernate:
#      create: 매번 table을 drop후 재생성
#      update : entity변경사항만 alter를 적용하고 기존데이터 유지.(모든 변경사항을 alter하는 것은 아님)
#      validate: 실제DDB와의 차이만을 check
      ddl-auto: create
#      콘솔창에 ddl, dml문을 출력하여 보여주는 옵션
    show_sql: true

#mapper파일(mybatis의 쿼리파일)의 위치를 명시. 기본적으로 resources 폴대 밑에 scan
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml